project:
  type: website

website:
  title: "Laetitia Drago"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Experience
        href: experience.qmd
      - text: Coding
        href: coding.qmd
      - text: Illustration
        href: illustration.qmd
    right:
      - text: "{{< iconify octicon:mark-github-16 >}}"
        href: "https://github.com/dlaetitia"
      - text: "{{< iconify simple-icons:googlescholar >}}"
        href: 'https://scholar.google.com/citations?user=HnReO8UAAAAJ&hl=en&authuser=1'
      - text: "{{< iconify fa6-brands:instagram >}}"
        href: 'https://www.instagram.com/marinelifetales/'
      - text: "{{< iconify fa6-brands:linkedin >}}"
        href: 'https://www.linkedin.com/in/laetitia-drago-926a58188/'

format:
  html:
    theme: litera  # Optional: Choose a theme
    css: styles.css  # Optional: Add custom CSS for further styling

