## Research experience

::: experience-item
::: experience-title
Post-doctoral position: Machine learning and marine data
:::

::: experience-date
March 2024 – Present
:::

LOCEAN Laboratory, Paris

Funding: <a href="https://neccton.eu/" target="_blank">NECCTON Horizon Europe project</a>

-   Spatial Distribution of Taxonomic and Functional Diversity of Zooplankton in the Iroise Sea Marine Park (<a href="https://parc-marin-iroise.fr/" target="_blank">PNMI</a>)
-   Use of quantitative imaging data (Zooscan), metabarcoding, environmental data and machine learning techniques
-   Investigation of the relationship between functional diversity and environmental factors
:::

::: experience-item
::: experience-title
PhD: Global Analysis of the Biological Carbon Pump Using Quantitative Imaging Data
:::

::: experience-date
2020 - 2023
:::

LOV UMR 7093, Villefranche sur mer, Sorbonne Université

Funding: 50% <a href="https://triatlas.w.uib.no/" target="_blank">H2020 European project TRIATLAS</a> and 50% Ecole Doctorale 129, Sorbonne Université

-   Spatial Distribution of Zooplankton Biomass Using Quantitative Imaging Data (UVP5) and Machine Learning (niche modeling)
-   Compilation of imaging and climatological data (WOA, Copernicus, NOAA)
-   Export phenomenon in the North Atlantic during the EXPORTS campaign, 2021
-   Scientific campaigns at sea: Norwegian Fjords and North Atlantic
:::

::: experience-item
::: experience-title
Master 2 internship: Global Distribution of Macroplankton Biomass Estimated by In Situ Imaging
:::

::: experience-date
2020 (6 months)
:::

LOV UMR 7093, Villefranche sur mer, Sorbonne Université

-   Spatial Distribution of Zooplankton Using Quantitative Imaging Data (UVP5) and Machine Learning (Niche modeling)
-   Analysis of a large dataset from 25 oceanographic projects
:::

::: experience-item
::: experience-title
M1 Internship: Numerical Simulations of Larval Dispersal of Paramuricea clavata
:::

::: experience-date
2019 (2 months)
:::

LECOB UMR 8222, Banyuls sur mer, Sorbonne Université

-   Lagrangian models of larval dispersal and population connectivity
:::

## Education

-   <strong>2022: FIDLE Introduction to Deep Learning, CNRS (17h)</strong>

Convolutional neural networks, evaluation of regression and classification models, sequential and temporal data. Theory and practice (Python).

-   <strong>2022: Ocean Litteracy, Sorbonne Université and IMBRSea (3 weeks)</strong>

Communicate with different types of audiences (age, profession) using innovative learning methods.

-   <strong>2021: Machine Learning 4 Ocean (ML4Ocean), Sorbonne Université (1 week)</strong>

Summer school on the use of artificial intelligence tools and machine learning in oceanography. Theory and practice (Python).

-   <strong>2018 - 2020: Master degree of Marine Sciences, Sorbonne Université</strong>

Functioning of marine ecosystems and global changes course obtained with honors.

Functional ecology, oceanography, modeling, data processing.

-   <strong>2018: Multivariate analyzes for marine ecology, Sorbonne Université (3 weeks)</strong>

Environmental data analysis methodologies. Theoretical and practical (R).

-   <strong>2015 - 2018: Bachelor of Science in Life and Health, Université de Nice </strong>

Biology of Organisms and Ecosystems course, obtained with honors.

Ecology, diversity of organisms and ecosystems, statistics, genetics.

## Awards and honors

-   <strong>December 2023:</strong> <a href="https://institut-ocean.sorbonne-universite.fr/actualites-institut-de-locean/prix-2023-de-la-publication-scientifique-fondation-de-la-mer-institut" target="_blank">Thesis Scientific Publication Award</a>, Foundation of the Sea and Ocean Institute of the Sorbonne University Alliance

-   <strong>2020 - 2023:</strong> Half PhD Scholarship, *Doctoral school 129, Sorbonne University*

-   <strong>September 2022:</strong> 2nd Place for best poster, *LOV laboratory seminar*

-   <strong>September 2021:</strong> 2nd Place for best poster, *TRIATLAS H2020 General Assembly*

## University Services

-   <strong>2020 - 2023: Co-organizer of "LOV Student Seminars"</strong>

Welcoming new PhD students and interns, organizing practice sessions for thesis defenses, and themed seminars

-   <strong>2020 - 2023: PhD Student Representative in Various Councils</strong>

    -   2022-2023: OSU-STAMAR Council

    -   2020-2023: Villefranche Oceanography Laboratory Council

    -   2020-2022: Villefranche Institute of the Sea Council

Advocating for doctoral students' interests, contributing to decision-making processes, and fostering communication between students and laboratory.

-   <strong>2018 - 2020: Co-organizer of "Green Lunch"</strong>

Organising weekly debates on environmental protection and sustainable development

## Teaching

-   <strong>May 2024 (6h): Green Ocean Course, ENSTA, Paris</strong>

Classes on Marine plankton diversity and biological invasions

-   <strong>March 2024 (3.5h): Tara Ocean QLife Winter School, ENS, Paris</strong>

Practical work on zooplankton distribution and in situ imaging data on R

-   <strong>2022 - 2023 (128h): Teaching Assistant Contract, 128h, Sorbonne University</strong>

Lectures and practical work with undergraduate and master's students on modeling, taxonomy, and plankton diversity.

-   <strong>Co-supervision of Internships</strong>

    -   Bachelor's 2nd Year: "Impact of the coastal front on phytoplankton dynamics in the Iroise Marine Natural Park", Sophia Mastouri, 2 weeks, 2024

    -   Master's 2nd Year: "Impacts of zooplankton on the carbon cycle of the equatorial Atlantic", Hélène Thibault, 6 months, 2022

    -   Master's 1st Year: "Study of zooplankton communities along the equatorial Atlantic", Hannah Haines, 2 months, 2021

## Communication

-   <strong>2023: Pint of Science </strong><a href="https://pintofscience.fr/event/plongee-dans-lunivers-insoupconne-de-la-mysterranee" target="_blank">"The Study of Zooplankton"</a>

Public outreach on zooplankton research

-   <strong>2021 - 2023: Scientific Animator, Petits débrouillards</strong>

Organized activities for various audiences, particularly on seas and coastlines.

-   <strong>2021 - 2022: Participation in EXPORTS Project Communication Campaign</strong>

    -   <a href="https://cce.nasa.gov/ocean_biology_biogeochemistry/postcards.html" target="_blank">Campaign postcard to NASA</a>

    -   <a href="https://divediscover.whoi.edu/" target="_blank">Interviews with the science communication team, Dive and Discover</a>

    -   <a href="https://blogs.nasa.gov/earthexpeditions/2021/06/22/imaging-the-ocean/" target="_blank">"Imaging the Ocean"</a>, blogpost for NASA Earth Expeditions

```{=html}
<!-- -->
```
-   <strong>2020: Translation of PlanktonID website</strong>

English to French translation: <a href="https://planktonid.geomar.de" target="_blank">PlanktonID Website</a>

## 
