## Research experience

::: experience-item
::: experience-title
Post-doctoral position: Machine learning and marine data
:::

::: experience-date
March 2024 – Present
:::

LOCEAN Laboratory, Paris

Funding: <a href="https://neccton.eu/" target="_blank">NECCTON Horizon Europe project</a>

-   Spatial Distribution of Taxonomic and Functional Diversity of Zooplankton in the Iroise Sea Marine Park (<a href="https://parc-marin-iroise.fr/" target="_blank">PNMI</a>)
-   Use of quantitative imaging data (Zooscan), metabarcoding, environmental data and machine learning techniques
-   Investigation of the relationship between functional diversity and environmental factors
:::

::: experience-item
::: experience-title
PhD: Global Analysis of the Biological Carbon Pump Using Quantitative Imaging Data
:::

::: experience-date
2020 - 2023
:::

LOV UMR 7093, Villefranche sur mer, Sorbonne Université

Funding: 50% <a href="https://triatlas.w.uib.no/" target="_blank">H2020 European project TRIATLAS</a> and 50% Ecole Doctorale 129, Sorbonne Université

-   Spatial Distribution of Zooplankton Biomass Using Quantitative Imaging Data (UVP5) and Machine Learning (niche modeling)
-   Compilation of imaging and climatological data (WOA, Copernicus, NOAA)
-   Export phenomenon in the North Atlantic during the EXPORTS campaign, 2021
-   Scientific campaigns at sea: Norwegian Fjords and North Atlantic
:::

::: experience-item
::: experience-title
Master 2 internship on Global Distribution of Macroplankton Biomass Estimated by In Situ Imaging
:::

::: experience-date
2020 (6 months)
:::

LOV UMR 7093, Villefranche sur mer, Sorbonne Université

-   Spatial Distribution of Zooplankton Using Quantitative Imaging Data (UVP5) and Machine Learning (Niche modeling)
-   Analysis of a large dataset from 25 oceanographic projects
:::

::: experience-item
::: experience-title
M1 Internship: Numerical Simulations of Larval Dispersal of Paramuricea clavata
:::

::: experience-date
2019 (2 months)
:::

LECOB UMR 8222, Banyuls sur mer, Sorbonne Université

-   Lagrangian models of larval dispersal and population connectivity
:::

## Education

::: experience-item
::: experience-title
FIDLE Introduction to Deep Learning, CNRS
:::

::: experience-date
2022 (17h)
:::

Convolutional neural networks, evaluation of regression and classification models, sequential and temporal data. Theory and practice (Python).
:::

::: experience-item
::: experience-title
Ocean Litteracy, Sorbonne Université and IMBRSea
:::

::: experience-date
2022 (3 weeks)
:::

Communicate with different types of audiences (age, profession) using innovative learning methods."
:::

::: experience-item
::: experience-title
Machine Learning 4 Ocean (ML4Ocean), Sorbonne Université
:::

::: experience-date
2021 (1 week)
:::

Summer school on the use of artificial intelligence tools and machine learning in oceanography. Theory and practice (Python).
:::

::: experience-item
::: experience-title
Master degree of Marine Sciences, Sorbonne Université
:::

::: experience-date
2018 - 2020
:::

Functioning of marine ecosystems and global changes course obtained with honors.

Functional ecology, oceanography, modeling, data processing.
:::

::: experience-item
::: experience-title
Multivariate analyzes for marine ecology, Sorbonne Université
:::

::: experience-date
2018 (3 weeks)
:::

Environmental data analysis methodologies. Theoretical and practical (R).
:::

::: experience-item
::: experience-title
Bachelor of Science in Life and Health, Université de Nice
:::

::: experience-date
2015 - 2018
:::

Biology of Organisms and Ecosystems course, obtained with honors.

Ecology, diversity of organisms and ecosystems, statistics, genetics.
:::

## Awards and honors

::: experience-item
::: experience-title
Thesis Scientific Publication Award
:::

::: experience-date
December 2023
:::

Awarded by the Foundation of the Sea and the Ocean Institute of the Sorbonne University Alliance
:::

::: experience-item
::: experience-title
2nd Place for Best Poster
:::

::: experience-date
September 2022
:::

LOV laboratory seminar
:::

::: experience-item
::: experience-title
2nd Place for Best Poster
:::

::: experience-date
September 2021
:::

General Assembly of the European TRIATLAS H2020 project
:::

::: experience-item
::: experience-title
Half PhD Scholarship
:::

::: experience-date
2020-2023
:::

Doctoral school 129 of Sorbonne University
:::

## University Services

::: experience-item
::: experience-title
Co-organizer of "LOV Student Seminars"
:::

::: experience-date
2020 - 2023
:::

<p>Welcoming new PhD students and interns, organizing practice sessions for thesis defenses, and themed seminars</p>
:::

::: experience-item
::: experience-title
PhD Student Representative in Various Councils
:::

::: experience-date
2020 - 2023
:::

<ul>

<li>2022-2023: OSU-STAMAR Council</li>

<li>2020-2023: Villefranche Oceanography Laboratory Council</li>

<li>2020-2022: Villefranche Institute of the Sea Council</li>

<li>Participated in bi-annual meetings of each council to highlight student needs</li>

</ul>
:::

::: experience-item
::: experience-title
Co-organizer of "Green Lunch"
:::

::: experience-date
2018 - 2020
:::

<p>Weekly debates on environmental protection and sustainable development</p>
:::

## Teaching and Communication

::: experience-item
::: experience-title
Tara Ocean QLife Winter School, ENS, Paris
:::

::: experience-date
March 2024 (3.5h)
:::

<p>Zooplankton distribution and in situ imaging data</p>
:::

::: experience-item
::: experience-title
Green Ocean Course, ENSTA, Paris
:::

::: experience-date
May 2024 (6h)
:::

<p>Marine plankton diversity and biological invasions</p>
:::

::: experience-item
::: experience-title
Teaching Assistant Contract, 128h, Sorbonne University
:::

::: experience-date
2022 - 2023
:::

<p>Lectures and practical work with undergraduate and master's students on modeling, taxonomy, and plankton diversity.</p>
:::

::: experience-item
::: experience-title
Pint of Science
:::

::: experience-date
2023
:::

<p><a href="https://pintofscience.fr/event/plongee-dans-lunivers-insoupconne-de-la-mysterranee" target="_blank">"The Study of Zooplankton"</a>: Public outreach on zooplankton research</p>
:::

::: experience-item
::: experience-title
Co-supervision of Internships
:::

::: experience-date
2021 - 2024
:::

<ul>

<li>Bachelor's 2nd Year: "Impact of the coastal front on phytoplankton dynamics in the Iroise Marine Natural Park", Sophia Mastouri, 2 weeks, 2024</li>

<li>Master's 2nd Year: "Impacts of zooplankton on the carbon cycle of the equatorial Atlantic", Hélène Thibault, 6 months, 2022</li>

<li>Master's 1st Year: "Study of zooplankton communities along the equatorial Atlantic", Hannah Haines, 2 months, 2021</li>

</ul>
:::

::: experience-item
::: experience-title
Participation in EXPORTS Project Communication Campaign
:::

::: experience-date
2021-2022
:::

<ul>

<li><a href="https://cce.nasa.gov/ocean_biology_biogeochemistry/postcards.html" target="_blank">Campaign postcard</a></li>

<li><a href="https://divediscover.whoi.edu/" target="_blank">Interviews with the science communication team, Dive and Discover</a></li>

<li><a href="https://blogs.nasa.gov/earthexpeditions/2021/06/22/imaging-the-ocean/" target="_blank">"Imaging the Ocean"</a>, blogpost for NASA Earth Expeditions</li>

</ul>
:::

::: experience-item
::: experience-title
Scientific Animator, Petits débrouillards
:::

::: experience-date
2021-2023
:::

<p>Organized activities for various audiences, particularly on seas and coastlines.</p>
:::

::: experience-item
::: experience-title
Translation of PlanktonID website
:::

::: experience-date
2020
:::

<p>English to French translation: <a href="https://planktonid.geomar.de" target="_blank">PlanktonID Website</a></p>
:::
